### ISSUE TITLE
[Bug]: Can access dashboard, even when not logged in

### ISSUE THREAD

**Issue by Amogh-Nivaskar** [piyushgarg-dev/review-app#102]
### Describe the bug

1. Currently one can still access the dashboard even when one is not logged in, or even when the user's authentication  token has expired. 

### To Reproduce

1. Logout of the application if you are logged in
2. Go to http://app.localhost:3000/dashboard
3. You are still able to access the dashboard

### Expected behavior

I think that if the user is not logged in or if their authentication token has expired, and he/she tries to access the dashboard or any of its child routes, the user should be redirected to the login page. We should protect this route. This leads to a better user experience. 

### Screenshots/Videos

![image](https://github.com/piyushgarg-dev/review-app/assets/99811918/386d78a9-1e99-4f40-a190-95760c9ffdf8)

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

**Comment by piyushgarg-dev** [comment]
Done @Amogh-Nivaskar

**Comment by Atharva1723** [comment]
@piyushgarg-dev Still the issue persist even if i have not  logged in . I can access the dashboard .Please assign me this issue
![image](https://github.com/piyushgarg-dev/review-app/assets/87201444/b87fb30c-4375-43bc-b001-f8d1feca3d6b)

**Comment by avdhendra** [comment]
is this issue resolve or i can take this issue
